defaults: &defaults
  aws_access_key_id: 'AKIAIL2H5XNBMCUID2NA'
  aws_secret_access_key: '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'
  email_bcc: 'srussell@blenderbox.com'
  email_from: ' <no-reply@nyccollegeline.org>'
  email_prefix: '[careers.nyccollegeline.org]'
  email_to: 'srussell@blenderbox.com'
  fog_directory: 'careermaps'
  fog_provider: 'AWS'
  host: 'http://careers.nyccollegeline.org'
  s3_host: 'careermaps.s3.amazonaws.com'

development:
  <<: *defaults
  s3_host: 'localhost:3000'
  secret_key_base: '9324172f6d7c37f096c65ed1fd4fcfeebc8581a5437a0e7e9185190dcb2931f87bc747f043d185282cef1f8965b7d59902f185260ccb00f4d7d4fa730b0d5b61'

test:
  <<: *defaults

stage:
  <<: *defaults
  email_prefix: '[stage.careermaps.bbox.ly]'
  fog_directory: 'careermaps-stage'
  host: 'http://stage.careermaps.bbox.ly'
  s3_host: 'careermaps-stage.s3.amazonaws.com'
  secret_key_base: '996574e5b37bf7856762c24a3450b8076ba9ec51fac3c26bdec253d9d559c5024fa5a4be4199757032d727810482c5a2087f6b2cada5d52d979551d8ea2c80af'

production:
  <<: *defaults
  email_prefix: '[careermaps.nyccollegeline.org]'
  fog_directory: 'careermaps'
  host: 'http://careermaps.nyccollegeline.org'
  s3_host: 'careermaps.s3.amazonaws.com'
  secret_key_base: '4ecfc1d56158313cb7bb75b5156f78c4796af597725bb6e0eb31a74006c65d2c8522e7f0f9dd44ae6641f1aacd891fe6899b5dc1772398cbacc0fe577fdc8325'
